
name: firebase_admin

repository: https://github.com/appsup-dart/firebase_admin


packages:
  - .

ide:
  intellij: false

command:
  version:
    linkToCommits: true

scripts:
  preversion: 
    exec: dart test -j 1


 